package org.yusufakbas.whispersafe.request;

public record UpdateUserRequestDto(String fullName, String profileImage) {

    public UpdateUserRequestDto {
        // Constructor body can be added here if needed
    }

    // Getters are automatically generated by record

    // Optionally, you can add additional methods if required
}